name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scans:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tfsec manually
        run: |
          curl -L -o tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.5/tfsec-linux-amd64
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/tfsec

      - name: Run tfsec scan
        run: tfsec ./terraform --config-file .tfsec/config.yml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: false
          tags: my-secure-app:latest
          load: true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: 'my-secure-app:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ameet56/my-secure-app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: security-scans
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate applying Kubernetes manifests
        run: |
          echo "Simulating deployment..."
          echo "Applying SealedSecret:"
          cat k8s/sealed-secret.yaml
          echo -e "\nApplying Deployment:"
          cat k8s/deployment.yaml

  apply-terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply Terraform configuration
        run: |
          echo "Simulating Terraform apply..."
          echo "Terraform plan would be applied here."
